# Generated by Django 5.1.4 on 2025-07-06 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(max_length=100)),
                ('numero_invitados', models.CharField(max_length=50)),
                ('fecha_evento', models.DateField()),
                ('servicios_adicionales', models.TextField(blank=True)),
                ('mensaje', models.TextField(blank=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('pendiente', 'Pendiente de pago'), ('pagada', 'Pagada')], default='abierta', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('comprobante_pago', models.FileField(blank=True, null=True, upload_to='comprobantes/')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
