# Generated by Django 5.1.4 on 2025-07-07 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cotizaciones', '0002_alter_cotizacion_tipo_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reservada', models.DateField()),
                ('creada_el', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='confirmada', max_length=20)),
                ('cotizacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cotizaciones.cotizacion')),
            ],
        ),
    ]
